receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlp:
    endpoint: http://jaeger:4317
    tls:
      insecure: true

  debug:
    verbosity: detailed
#otlp pointe vers jagger
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp]