apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: auth-service

  template:
    metadata:
      labels:
        app: auth-service

    spec:
      containers:
        - name: auth-service
          image: maknos/auth-service:latest

          ports:
            - containerPort: 3002

          env:
            - name: DB_HOST
              value: postgres

            - name: DB_PORT
              value: "5432"

            - name: DB_USERNAME
              value: root

            - name: DB_PASSWORD
              value: root

            - name: DB_NAME
              value: velora_postgres