name: Velora CI/CD Pipeline

on:
  push:
    branches:
      - pipeline
  pull_request:
    branches:
      - pipeline

jobs:

  backend-build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        service:
          - auth-service
          - user-service
          - admin-service
          - customer-service
          - dashboard-service

    defaults:
      run:
        working-directory: backend/velora-platform/${{ matrix.service }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        continue-on-error: true

      - name: Build service
        run: npm run build
        continue-on-error: true

      - name: Run tests
        run: npm test
        continue-on-error: true

      - name: Security audit
        run: npm audit --audit-level=high
        continue-on-error: true

  frontend-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install frontend dependencies
        run: npm install --legacy-peer-deps
        continue-on-error: true

      - name: Build frontend
        run: npm run build
        continue-on-error: true

      - name: Security audit frontend
        run: npm audit --audit-level=high
        continue-on-error: true